function [bit,ip,jp] = isInvolutive(x,mat)
    % This function decides whether the distribution mat, whose vector fields 
    % are described by its columns is involutive or not.
    % A distribution is invoultive iff for any i and j <= n-2,  [fi,fj] belongs 
    % in the distribution, i.e. the new vector field [fi,fj] is in the subspace
    % spanned by the initial vector fields
    
    ip=-1;
    jp=-1;
    [imax,jmax]=size(mat);
    if imax<=jmax 
        return
    end

    bit =true;
    
    for i=1:jmax
        for j=1:jmax
            a=lie_bracket(x,mat(:,i),mat(:,j),1);
    %       a(:,2) is in the subspace generated by mat ?
            newmat=[mat,a(:,2)];
            if(rank(newmat)~=rank(mat))
                bit = false;
                ip=i;
                jp=j;
                return;
            end
        end
    end
end